In [1]:
# Library Imports
import pandas as pd
import plotly.express as px
import json

In [2]:
# Data Source
df = pd.read_csv('files/PopulationByCounty1841-2022.csv')

In [3]:
# Printing data to test
df.head()

             Statistic Label  CensusYear  County         Sex    UNIT    VALUE
0  Population at Each Census        1841   State  Both sexes  Number  6528799
1  Population at Each Census        1841   State        Male  Number  3222485
2  Population at Each Census        1841   State      Female  Number  3306314
3  Population at Each Census        1841  Carlow  Both sexes  Number    86228
4  Population at Each Census        1841  Carlow        Male  Number    42428

### Note:
Next step is to pivot this df so that each county has one row per year. The 'Male', 'Female' and 'Both sexes' will get their own column. The *UNIT* and *Statistic Label* columns will be dropped. I will be using the Pandas [*pivot_table*](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html) function to perform this transformation.

In [4]:
census_pop = df.pivot_table(
    index=["CensusYear","County"], 
    columns="Sex",
    values="VALUE",
    aggfunc="sum"
).reset_index()

census_pop.columns.name=None
census_pop = census_pop.rename_axis(None, axis=1)

# Rename Column
census_pop.rename(columns={"Both sexes": "FMCombined"}, inplace=True)

# Re-ordering Columns
census_pop = census_pop[["CensusYear", "County", "Female", "Male", "FMCombined"]]

In [5]:
census_pop

     CensusYear     County  Female    Male  FMCombined
0          1841     Carlow   43800   42428       86228
1          1841      Cavan  122344  120814      243158
2          1841      Clare  142285  144109      286394
3          1841       Cork  433567  420551      854118
4          1841    Donegal  150627  145821      296448
..          ...        ...     ...     ...         ...
697        2022  Tipperary   84256   83639      167895
698        2022  Waterford   64268   63095      127363
699        2022  Westmeath   48500   47721       96221
700        2022    Wexford   83142   80777      163919
701        2022    Wicklow   79287   76564      155851

[702 rows x 5 columns]

I want to plot the above data using [Plotly](https://plotly.com/python/getting-started/#jupyter-notebook-support) and will toy around with the various plot/graph/chart types below. The first few plots will be a national outlook and I will then focus on the regional area under the [Western Development Commision's](https://westerndevelopment.ie/) remit - **Clare**, **Galway**, **Mayo**, **Roscommon**, **Sligo**, **Leitrim** and **Donegal**. As an area that I was born in to, emigrated from and returned to raise a family in, I have a vested interest in the region's success and analysis of the population should form part of any meaningful analysis for this area.

In [6]:
# Male vs Female population trends
cp_year = census_pop.groupby("CensusYear")[["Male", "Female", "FMCombined"]].sum().reset_index()

fig = px.line(
    cp_year,
    x="CensusYear",
    y=["Male", "Female", "FMCombined"],
    title="Population of Ireland by Sex Over Time",
    labels={"value": "Population", "CensusYear": "Year", "variable": "Sex"}
)
fig.show()

In [7]:
# Defined County Population Comparison of Male vs Female

fig = px.line(
    census_pop[census_pop["County"] == "Dublin"],
    x="CensusYear",
    y=["Male", "Female"],
    title="Male vs Female Population in Dublin Over Time",
    labels={"value": "Population", "CensusYear": "Year", "variable": "Sex"}
)
fig.show()

In [8]:
fig = px.line(
    census_pop[census_pop["County"] == "Mayo"],
    x="CensusYear",
    y=["Male", "Female"],
    title="Male vs Female Population in Mayo Over Time",
    labels={"value": "Population", "CensusYear": "Year", "variable": "Sex"}
)
fig.show()

In [9]:
fig = px.line(
    census_pop[census_pop["County"] == "Roscommon"],
    x="CensusYear",
    y=["Male", "Female"],
    title="Male vs Female Population in Roscommon Over Time",
    labels={"value": "Population", "CensusYear": "Year", "variable": "Sex"}
)
fig.show()

In [10]:
fig = px.bar(
    census_pop[census_pop["CensusYear"] == 2022],
    x="County",
    y=["Male", "Female"],
    barmode="group",
    title="Population by County and Sex (2022)",
    labels={"value": "Population", "variable": "Sex"}
)
fig.show()

In [11]:
census_pop["Male_to_Female_Ratio"] = census_pop["Male"] / census_pop["Female"]

fig = px.line(
    census_pop.groupby("CensusYear")["Male_to_Female_Ratio"].mean().reset_index(),
    x="CensusYear",
    y="Male_to_Female_Ratio",
    title="Average Male-to-Female Ratio Over Time",
)
fig.show()

## Using a Choropleth Map
---
The Plotly libary offers a *choropleth* function that adds mapping to the visualisations. I sourced an Irish GeoJSON file on [GitHub from 'vool'](https://gist.github.com/vool/969e3be0cfac519560755cce0b91e097#file-ireland-geojson). [The Choropleth documentation from Plotly](https://plotly.com/python/choropleth-maps/) was used to attempt this.

In [12]:
#import plotly.io as pio
#pio.renderers.default = 'notebook'  # 'iframe_connected' for GitHUb CodeSpace


# Load the GeoJSON data
#with open("files/ireland.geojson") as f:
#    counties_geo = json.load(f)

# 

#fig = px.choropleth(
#    census_pop.assign(Both=census_pop["Male"] + census_pop["Female"]),
#    geojson=counties_geo,
#    locations="County",
#    featureidkey="properties.NAME_TAG",
#    color="Both",
#    hover_name="County",
#    animation_frame="CensusYear",
#    color_continuous_scale="Viridis",
#    title="Population by County Over Time"
#)
#fig.update_geos(fitbounds="locations", visible=False)
#fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
#fig.show(renderer="notebook")

#fig.write_html("files/choropleth_map.html")

## Note:

I will not pursue this particular mapping visualisation as despite following the documentation, I am not successfully generating the visualisation.

### [Standard Deviation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.std.html)
---
[$$s = \sqrt{\frac{1}{n - 1} \sum_{i=1}^{n} (x_i - \bar{x})^2}$$](https://en.wikipedia.org/wiki/Standard_deviation)

In [13]:
# Calculating Change Between Census
census_pop = census_pop.sort_values(["County", "CensusYear"])
census_pop["PopChange"] = census_pop.groupby("County")["FMCombined"].diff()

In [14]:
# Standard Deviation
county_std = census_pop.groupby("County")["PopChange"].std().reset_index()
county_std.columns = ["County", "StdDev"]

In [15]:
county_std

       County         StdDev
0      Carlow    5162.459088
1       Cavan   15013.173204
2       Clare   18318.988858
3        Cork   51922.761566
4     Donegal   12394.587972
5      Dublin   35921.898643
6      Galway   28785.272451
7       Kerry   14518.088285
8     Kildare   12502.995288
9    Kilkenny   12141.482426
10      Laois   10744.372451
11    Leitrim    8984.614539
12   Limerick   18620.923036
13   Longford    7405.952066
14      Louth    7992.121986
15       Mayo   23604.217493
16      Meath   16336.230432
17   Monaghan   12621.115771
18     Offaly    9204.639471
19  Roscommon   16549.952416
20      Sligo   11150.058935
21      State  384027.315908
22  Tipperary   27099.661420
23  Waterford   10680.634994
24  Westmeath    8653.802048
25    Wexford   11436.790077
26    Wicklow    9431.616708

In [16]:
# Merging Standard Deviation back in to DF
census_pop = census_pop.merge(county_std, on="County", how="left")

In [17]:
# Box Plot
fig = px.box(
    census_pop,
    x="County",
    y=["PopChange"],
    title="Distribution of Population Changes by County Over Time",
    points="all", 
    color="County"
)
fig.update_layout(xaxis_tickangle=-45)
fig.show()

### Note:
The population change as an absolute is understandable but arguably less palatable than a percentage. Let's calculate the change as a percentage.

In [18]:
census_pop['GrowthRate'] = census_pop.groupby('County')['FMCombined'].pct_change() * 100
census_pop['GrowthRate']

0            NaN
1     -21.048847
2     -16.071271
3      -9.603234
4      -9.839303
         ...
697    11.679635
698    10.043950
699     8.277731
700     4.233753
701     9.426716
Name: GrowthRate, Length: 702, dtype: float64

### Note:
I am now going to group the 7 counties under the remit of Western Development Commision.

In [19]:
# Defining the WDC group
wdc = ["Clare", "Galway", "Mayo", "Roscommon", "Sligo", "Leitrim", "Donegal"]

# Separating WDC Group From The Rest
df_wdc = census_pop[census_pop["County"].isin(wdc)]
df_state = census_pop[census_pop["County"] == "State"]

In [20]:
df_wdc

,CensusYear,County,Female,Male,FMCombined,Male_to_Female_Ratio,PopChange,StdDev,GrowthRate
52,1841,Clare,142285,144109,286394,1.012819,NaN,18318.988858,NaN
53,1851,Clare,108487,103953,212440,0.958207,-73954.0,18318.988858,-25.822468
54,1861,Clare,83764,82541,166305,0.985399,-46135.0,18318.988858,-21.716720
55,1871,Clare,74422,73442,147864,0.986832,-18441.0,18318.988858,-11.088662
56,1881,Clare,70399,71058,141457,1.009361,-6407.0,18318.988858,-4.333036
...,...,...,...,...,...,...,...,...,...
541,2002,Sligo,29429,28771,58200,0.977641,2379.0,11150.058935,4.261837
542,2006,Sligo,30637,30257,60894,0.987597,2694.0,11150.058935,4.628866
543,2011,Sligo,32958,32435,65393,0.984131,4499.0,11150.058935,7.388248
544,2016,Sligo,33170,32365,65535,0.975731,142.0,11150.058935,0.217149
545,2022,Sligo,35669,34529,70198,0.968039,4663.0,11150.058935,7.115282

In [ ]:
# Visualising Standard Deviation